### ISSUE TITLE
Problem with the local SSL certificate

### ISSUE THREAD

**Issue by GenryMorgan777** [KriseevM/vkschoolbot#36]
Подключил ssl к хосту через certbot, создал и прописал в конфиге клиентский сертификат, но все равно выдает ошибку
Problem with the local SSL certificate

**Comment by KriseevM** [comment]
А что за сервер используется (я имею в виду программу - apache, nginx...)? И желательно уточнить как именно сделан конфиг, а также более подробно расписать, что сделано, чтобы я мог попробовать у себя воспроизвести эту проблему

**Comment by GenryMorgan777** [comment]
Nginx

**Comment by GenryMorgan777** [comment]
Лучше напиши, как у тебя конфиг прописан

**Comment by KriseevM** [comment]
Я просто на apache работал и тестировал. Я попробую сегодня-завтра настроить. Если будет работать - скину, как у меня настроено

**Comment by GenryMorgan777** [comment]
Я могу Apache поставить, напиши только как настроить

**Comment by KriseevM** [comment]
Apache тоже несложно настраивается
Почти все по настройке бота в wiki описано как раз для него
А по поводу самого сервера и ssl к нему - вроде через certbot тоже со стандартными настройками всё прекрасно работает. Ну, для примера можно вот на TProger гайд посмотреть https://tproger.ru/articles/set-up-and-configure-an-apache-server/

**Comment by GenryMorgan777** [comment]
Поставил я сервер на Apache подключил и создал ssl сертификаты, сделал обязательную проверку клиентского сертификата. Проверил на себе: сертификат принимает и пускает на сайт.
А вк опять пишет "Problem with the local SSL certificate"

**Comment by KriseevM** [comment]
В общем, я пока ничего не могу по поводу решения этой проблемы сказать. Я посмотрю в ближайшие пару дней, и постараюсь, может быть, дать какие-то рекомендации

**Comment by GenryMorgan777** [comment]
Эту ошибку решил, появилась новая 
HTTP response code said error

**Comment by GenryMorgan777** [comment]
Нашел вот такую информацию 
https://qna.habr.com/q/718453

**Comment by KriseevM** [comment]
А можно спросить, как была решена первая проблема?

**Comment by KriseevM** [comment]
По поводу второй проблемы - попробуй там в файле index.php исправить error_reporting с Off на On и будет в ответе видна ошибка

**Comment by KriseevM** [comment]
Потом главное вернуть обратно в положение Off, чтобы не было проблем с ответами сервера

**Comment by GenryMorgan777** [comment]
Решил проблему, установкой бота на Apache, если устанавливаете на nginx нужно прописывать в конфиг использование php и в целом правильно его установить.
