### ISSUE TITLE
Бот не реагирует на команды

### ISSUE THREAD

**Issue by GenryMorgan777** [KriseevM/vkschoolbot#37]
Пишу в сообщения группы ВКонтакте, к которой привязан бот- никакой реакции. Может быть токен группы не правильно указал?("указал его в кавычках")

**Comment by GenryMorgan777** [comment]
Можешь дать контакт свой постоянный?

**Comment by KriseevM** [comment]
Попробуй посмотри, там на странице, где callback api настраивать - можно посмотреть отправленные запросы и 
возникшие ошибки. Обычно это либо проблемы с правами на файлы, либо проблемы с настройкой сервера (надо будет для этого сделать отдельную страницу в wiki когда-нибудь). 
По поводу контакта - можно в ВК мне писать, в принципе vk.com/kriseev1
